select * from T_REPERTORYCHILD with(nolock) where FINWAREHOUSEID=6
update T_REPERTORYCHILD set FBARCODE='11 11 11 2'

update T_REPERTORYCHILD set FENABLE=2.6 where FGUID='68631A60-640B-4F6E-910D-8221A290A354'
update T_REPERTORYCHILD set FENABLE=30 where FGUID='EECDA9AD-5A36-44E1-842E-EB8CD0A48681'


select * from T_GOODSBACKDETAILS where FPARENTID='9a7c719b-e94c-4087-9f7b-e2826d6f90eb'

update T_GOODSBACKDETAILS set FPARENTID='9a7c719b-e94c-4087-9f7b-e2826d6f90eb' 

select min(FOUTWAREHOUSEID) as FOUTWAREHOUSEID,min(FINWAREHOUSEID) FINWAREHOUSEID,min(FBARCODE) as FBARCODE,
min(FGOODSID) as FGOODSID,min(FGOODSNAME) as FGOODSNAME,min(FUNIT) as FUNIT,SUM(FQUANTITY) as FQUANTITY,SUM(FSURPLUS) as FSURPLUS,
SUM(FENABLE) as FENABLE,min(FPRICE) as FPRICE,
(select b.FMARKETPRICE from T_GUIDANCE a with(nolock) left join T_GUIDANCEDETAILS b with(nolock) on a.FGUID=b.FPARENTID where a.FWAREHOUSEID=3 and a.FDATE=convert(varchar(10),getdate(),120) and b.FGOODSID=min(c.FGOODSID)) as FMARKETPRICE
from T_REPERTORYCHILD c with(nolock) where FINWAREHOUSEID=6 group by FBARCODE



select b.FMARKETPRICE from T_GUIDANCE a left join T_GUIDANCEDETAILS b on a.FGUID=b.FPARENTID where a.FWAREHOUSEID=3 and a.FDATE=convert(varchar(10),getdate(),120) and b.FGOODSID=12
